#frozen_string_literal: true

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(
    skip_upload_apk: true,
    skip_upload_images: true,
    skip_upload_metadata: true,
    skip_upload_screenshots: true,
      track: "internal",
      )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
